import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "abhay",
      email: "abhaybharti@gmail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "awanish",
      email: "awanish@gmail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      //_id: "1",
      name: "Men Regular Fit Solid Spread Collar Casual Shirt",
      slug: "Men-Regular-Fit-Solid-Spread-Collar-Casual-Shirt",
      category: "Cloths",
      subcategory: "Shirts",
      image:
        "/images/clothGreenFlairshirt1.png!/images/clothGreenFlairshirt2.png",
      price: 120,
      countInStock: 10,
      brand: "GreenFlair ",
      rating: 4.5,
      numReviews: 10,
      description:
        "Regular!Full Sleeve!Machine wash as per tag!Western Wear!This shirt is made in cargo shirt pattern and slightly casual pattern, so you can use this shirt in party and casual both occassions.!A best quality of cotton fabric is used to create this cotton cargo shirt by GREENFLAIR.",
      isFeatured: true,
      banner: "/images/bannershopbeauty.jpg",
    },
    {
      // _id: "2",
      name: "Men Regular Fit Striped Spread Collar Casual Shirt",
      slug: "Men-Regular-Fit-Striped-Spread-Collar-Casual-Shirt",
      category: "Cloths",
      subcategory: "Shirts",
      image:
        "/images/clothbellstoneshirt1.png!/images/clothbellstoneshirt2.png",
      price: 110,
      countInStock: 10,
      brand: "bellstone",
      rating: 4.5,
      numReviews: 10,
      description:
        "Regular!Cotton Blend!Full Sleeve!Gentle Machine Wash!Our fabrics are pre-washed to avoid shrinkage, and in certain cases, treated with Enzymes to give a softer, more comfortable feel. Many of our fabrics are treated with easy-care washes, to make ironing easier. Ultimately, the selection of your dress fabric will be a careful consideration of the Ply, Count, Composition and Weave.",
      isFeatured: true,
      banner: "/images/bannershopbook.jpg",
    },
    {
      // _id: "3",
      name: "Adidas Slim Shirt",
      slug: "adidas-slim-shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 100,
      countInStock: 100,
      brand: "adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      isFeatured: true,
      banner: "/images/bannershopgame.jpg",
    },
    {
      // _id: "4",
      name: "Nike Pant",
      slug: "nike-pant",
      category: "Shirts",
      image: "/images/p4.jpg",
      price: 130,
      countInStock: 10,
      brand: "adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      isFeatured: true,
      banner: "/images/bannershopholiday.jpg",
    },
    {
      // _id: "4",
      name: "Nike Shirt",
      slug: "nike-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 130,
      countInStock: 10,
      brand: "adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      isFeatured: true,
      banner: "/images/bannershopholiday.jpg",
    },
    {
      // _id: "4",
      name: "India Shirt",
      slug: "india-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 130,
      countInStock: 10,
      brand: "adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      isFeatured: true,
      banner: "/images/bannershopholiday.jpg",
    },
    {
      // _id: "4",
      name: "Banga Shirt",
      slug: "banga-shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 130,
      countInStock: 10,
      brand: "adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      // _id: "4",
      name: "BLUE HEAVEN Silk & Stain Lip Tint, Showgirl Pink",
      slug: "BLUE HEAVEN Silk & Stain Lip Tint, Showgirl Pink",
      category: "Cosmetic",
      image: "/images/shirt3.jpg",
      price: 130,
      countInStock: 10,
      brand: "BLUE HEAVEN",
      rating: 4.5,
      numReviews: 10,
      description:
        "BLUE HEAVEN Silk & Stain Lip Tint, Showgirl Pink, 8ml Lip Stain  (8 ml)",
    },
  ],
};

export default data;
