import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "abhay",
      email: "abhaybharti@gmail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "awanish",
      email: "awanish@gmail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      //_id: "1",
      name: "Nike Slim Shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      isFeatured: true,
      banner: "/images/bannershopbeauty.jpg",
    },
    {
      // _id: "2",
      name: "Nike Slim Pant",
      slug: "nike-slim-pant",
      category: "Pants",
      image: "/images/p2.jpg",
      price: 110,
      countInStock: 10,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      isFeatured: true,
      banner: "/images/bannershopbook.jpg",
    },
    {
      // _id: "3",
      name: "Adidas Slim Shirt",
      slug: "adidas-slim-shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 100,
      countInStock: 100,
      brand: "adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      isFeatured: true,
      banner: "/images/bannershopgame.jpg",
    },
    {
      // _id: "4",
      name: "Nike Pant",
      slug: "nike-pant",
      category: "Shirts",
      image: "/images/p4.jpg",
      price: 130,
      countInStock: 10,
      brand: "adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      isFeatured: true,
      banner: "/images/bannershopholiday.jpg",
    },
    {
      // _id: "4",
      name: "Nike Shirt",
      slug: "nike-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 130,
      countInStock: 10,
      brand: "adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      isFeatured: true,
      banner: "/images/bannershopholiday.jpg",
    },
    {
      // _id: "4",
      name: "India Shirt",
      slug: "india-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 130,
      countInStock: 10,
      brand: "adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      isFeatured: true,
      banner: "/images/bannershopholiday.jpg",
    },
    {
      // _id: "4",
      name: "Banga Shirt",
      slug: "banga-shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 130,
      countInStock: 10,
      brand: "adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};

export default data;
